steps:
  # GitHub Checks に Cloud Build の実行を通知するため、開始時に in_progress を登録する。
  - name: python:3.11-slim
    id: create-github-check
    entrypoint: python
    env:
      - GITHUB_CHECKS_TOKEN=$_GITHUB_CHECKS_TOKEN
      - GITHUB_REPOSITORY=$_GITHUB_REPOSITORY
      - GITHUB_SHA=$_GITHUB_SHA
      - GITHUB_RUN_URL=$_GITHUB_RUN_URL
    args:
      - -c
      - |
        import datetime as dt
        import json
        import os
        import urllib.request

        token = os.environ.get("GITHUB_CHECKS_TOKEN", "")
        repo = os.environ.get("GITHUB_REPOSITORY", "")
        sha = os.environ.get("GITHUB_SHA", "")
        run_url = os.environ.get("GITHUB_RUN_URL", "")

        if not (token and repo and sha):
            print("GitHub Checks API skipped (missing token/repo/sha).")
            raise SystemExit(0)

        url = f"https://api.github.com/repos/{repo}/check-runs"
        payload = {
            "name": "Cloud Build (backend)",
            "head_sha": sha,
            "status": "in_progress",
            "started_at": dt.datetime.now(dt.timezone.utc).isoformat(),
        }
        if run_url:
            payload["details_url"] = run_url

        req = urllib.request.Request(
            url,
            data=json.dumps(payload).encode("utf-8"),
            method="POST",
            headers={
                "Accept": "application/vnd.github+json",
                "Authorization": f"Bearer {token}",
                "X-GitHub-Api-Version": "2022-11-28",
            },
        )
        with urllib.request.urlopen(req, timeout=30) as resp:
            body = json.loads(resp.read().decode("utf-8"))
        check_id = body.get("id")
        if not check_id:
            raise SystemExit("Failed to create GitHub check-run (missing id).")
        with open("/workspace/github-check-run-id.txt", "w", encoding="utf-8") as fh:
            fh.write(str(check_id))

  # Cloud Run 用のバックエンドイメージを Dockerfile.backend でビルドします。
  # repo-root の Dockerfile がアップロードに含まれないケースでも、こちらは明示指定で動作します。
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.backend
      - -t
      - $_IMAGE_URI
      - .

  # 成功したビルド結果を GitHub Checks に反映する。
  - name: python:3.11-slim
    id: complete-github-check
    entrypoint: python
    env:
      - GITHUB_CHECKS_TOKEN=$_GITHUB_CHECKS_TOKEN
      - GITHUB_REPOSITORY=$_GITHUB_REPOSITORY
      - GITHUB_RUN_URL=$_GITHUB_RUN_URL
    args:
      - -c
      - |
        import datetime as dt
        import json
        import os
        import pathlib
        import urllib.request

        token = os.environ.get("GITHUB_CHECKS_TOKEN", "")
        repo = os.environ.get("GITHUB_REPOSITORY", "")
        run_url = os.environ.get("GITHUB_RUN_URL", "")
        check_id_path = pathlib.Path("/workspace/github-check-run-id.txt")

        if not (token and repo and check_id_path.exists()):
            print("GitHub Checks API completion skipped (missing token/repo/check id).")
            raise SystemExit(0)

        check_id = check_id_path.read_text(encoding="utf-8").strip()
        url = f"https://api.github.com/repos/{repo}/check-runs/{check_id}"
        payload = {
            "status": "completed",
            "conclusion": "success",
            "completed_at": dt.datetime.now(dt.timezone.utc).isoformat(),
            "output": {
                "title": "Cloud Build succeeded",
                "summary": "Cloud Build が成功しました。詳細は Cloud Build のログを参照してください。",
            },
        }
        if run_url:
            payload["details_url"] = run_url

        req = urllib.request.Request(
            url,
            data=json.dumps(payload).encode("utf-8"),
            method="PATCH",
            headers={
                "Accept": "application/vnd.github+json",
                "Authorization": f"Bearer {token}",
                "X-GitHub-Api-Version": "2022-11-28",
            },
        )
        with urllib.request.urlopen(req, timeout=30) as resp:
            resp.read()

images:
  - $_IMAGE_URI
